### ISSUE TITLE
Change 'salt' to 'salty' for Salinity in Database

### ISSUE THREAD

**Issue by PhoenixTilea** [Nerdbuilding/Generator_Issue_Tracker#10]
To bring the naming more in line with the rest of our terms and so it will look better in display, we should change "salt" when referring to possible salinity ranges of water features and tolerance of fish to "salty" instead. (This was my fault. Dunno' why I did it this way in the code).

**Comment by thebeardedheathen** [comment]
All "salt" tags for fish salinity have been updated to "salty"
