### ISSUE TITLE
Stone generation not using "Temperature Zone" filtering

### ISSUE THREAD

**Issue by thebeardedheathen** [Nerdbuilding/Generator_Issue_Tracker#104]
A user received a generation where "laterite" had generated in a polar region, which should not have been possible due to filtering constraining "laterite" generation to tropical and subtropical regions.

**Comment by PhoenixTilea** [comment]
The code should handle this if the data is in the correct format. Does the stone category itself list temperature zone in its filters?

**Comment by thebeardedheathen** [comment]
This was caused by a misspelled attribute.l
