### ISSUE TITLE
Ability to "Exclude" selections of information from the export.

### ISSUE THREAD

**Issue by thebeardedheathen** [Nerdbuilding/Generator_Issue_Tracker#108]
A couple users submitted feedback wondering if it would be possible to exclude certain, user selected, portions of the generated settlement from being included in the export of the settlement, rather than exporting everything and then needing to delete the information they do not want.

**Comment by PhoenixTilea** [comment]
I think we could implement excluding broad sections - basically anything headed by an h2 tag. Anything more fine-grained could get messy, but there might be exceptions.

**Comment by thebeardedheathen** [comment]
I would think that excluding h2 sections would be a really good start. Considering we are currently outputting over 300 pieces, and that is just going to grow, getting super granular this early would make for huge amounts of work later on. So to keep it simple, larger sections would be a perfect thing to practice with.

**Comment by PhoenixTilea** [comment]
Done and on staging site
