### ISSUE TITLE
Site Looks Like Ass on Mobile

### ISSUE THREAD

**Issue by PhoenixTilea** [Nerdbuilding/Generator_Issue_Tracker#11]
Yeah... We're aware of this and really hope to get it looking good no matter your screen. Unfortunately, this will require help from an actual UX designer/developer. I might be able to make some adjustments that could help, but being blind, there's only so much I can do on memory alone.

**Comment by thebeardedheathen** [comment]
Yes, mobile access accounts for a massive portion of internet usage, and mobile friendly sites are almost a necessity. However, we will be focusing on information generation and utility of the generator, before we focus on making a mobile friendly version of the generator.

We need to know what we are working with, before we can optimize a mobile friendly version.

For the near/foreseeable future, we will not be developing for mobile. I apologize if this hinders your use of our generator. But, we need to focus on the information first.

**Comment by thebeardedheathen** [comment]
Closing this and re-opening a new Mobile Issue to better capture our work on making the generator more mobile friendly.
