### ISSUE TITLE
Population Density Option

### ISSUE THREAD

**Issue by thebeardedheathen** [Nerdbuilding/Generator_Issue_Tracker#13]
I have had a few concerns about population density, and the ability to decide the number of inhabitants of a settlement.

This might have to be a range of Residential buildings based on the settlement type.
For example, we could have a town with 1000+ residential buildings, but only  2800 people. If we increased the population to satisfy a high/normal density, it would change to a large town, or small city. However, if we made it to decrease the number of residential buildings, that would keep the settlement as what it is, and just reduce one number, instead of changing a lot of other things.

**Comment by PhoenixTilea** [comment]
An option to select population density and the backend refactor have been done in #14
