### ISSUE TITLE
Generation Errors with Large Settlements in Lagoons

### ISSUE THREAD

**Issue by PhoenixTilea** [Nerdbuilding/Generator_Issue_Tracker#19]
Because of the way we handle water features and the various places they could come from, landscapes like the Lagoon which wont generate with any large bodies of fresh water create problems when a user specifically selects a large settlement. The dropdown filtering definitely still needs work to make it more robust, but for now, blacklisting those landscapes on those larger settlements should fix the issue.

This will need to be done in the database and taken into account in code.

**Comment by thebeardedheathen** [comment]
Database has been updated.
