### ISSUE TITLE
Building Constructions in Areas With Heavy Rainfall

### ISSUE THREAD

**Issue by PhoenixTilea** [Nerdbuilding/Generator_Issue_Tracker#2]
A user brought up the concern that certain basic building materials such as sun-dried bricks wouldn't do so well in areas with a lot of rain (like rain forests). We need to look into what materials wouldn't stand up as well in very wet environments and implement a way to constrict these materials based on either biome or directly on rainfall.

**Comment by thebeardedheathen** [comment]
This brings up a pretty interesting idea. Right now we have a single point of information for building materials. Perhaps we could increase that to "Structure materials" and "Roofing Materials"? Though, yes. pure mud brick, wattle and daube, and earthen materials would need to be restricted.

Also maybe in addition to some of the other "Infrastructure" items, we could add in "drainage" as a new metric?

**Comment by thebeardedheathen** [comment]
Added rainfall restrictions to certain types of construction.
