### ISSUE TITLE
More Early Seniors Assigned to Professions than Exist in Settlement

### ISSUE THREAD

**Issue by PhoenixTilea** [Nerdbuilding/Generator_Issue_Tracker#24]
Bug Report from production:
"sum of profession breakdown exceeds the amount of early seniors. I'm guessing that early seniors aren't holding multiple jobs (or is this the future for American millennials?)"

I've verified in the settlement that this is indeed happening. I'm not sure if it's happening with other age groups just yet.

**Comment by thebeardedheathen** [comment]
It has also happened with the "Middle Aged" group. But I have not seen an overuse of other age groups yet.

**Comment by PhoenixTilea** [comment]
Fixed this issue and rebalanced how people are assigned to professions in general. Hopefully the numbers will be more in line with the population segments now.
