### ISSUE TITLE
Clarity Between Crops versus Foragables

### ISSUE THREAD

**Issue by PhoenixTilea** [Nerdbuilding/Generator_Issue_Tracker#25]
Feedback from a user:
"If a fruit tree is in the list, the fruit should be in the list of crops/fruits. For instance, this generation has Peach trees, so I would expect a Peach to be in the fruit section (same with Apple, Orange, maybe cherry, etc)"

It isn't perfectly clear that the "crops" are meant to be cultivated crops, and it probably doesn't help that we don't quite have forage/other natural resources implemented yet. I'm thinking of maybe changing the "crops" label on the overview to "cultivated crops". As for fruits in resources, maybe it would be good to lump it all together, because whether or not they are specifically cultivating a fruit, it's still a fruit. We'll need to discuss how we're going to handle resources going forward.

**Comment by thebeardedheathen** [comment]
That does bring up a good point. In the "Resources" tab, for items like lumber and stone, we list every type available to the settlement and then identify which of those resources are actively being worked through mines, logging camps etc.

I know we had originally intended to have the Fruit section only show the fruits which were being cultivated, but perhaps it could include all fruits and then we can identify which ones are being actively cultivated. The foraging section could then be used for actual forage centered resources, like mushrooms, certain herbs and flowers, etc.

**Comment by PhoenixTilea** [comment]
I've changed the label of Crops on the overview to Cultivated Crops, addressing the basic issue of the ticket. We'll make follow-up tickets as we go forward with splitting out flora, fauna, and resources.
