### ISSUE TITLE
Flora and Fauna Tab

### ISSUE THREAD

**Issue by PhoenixTilea** [Nerdbuilding/Generator_Issue_Tracker#39]
We put the local flora in the geography panel and fauna - currently wild animals - in the resources tab in order to display the information somewhere. However, we are starting to accumulate a lot of information on both and neither really fits where it is right now. We believe there will be enough info to warrant its own tab.

**Comment by thebeardedheathen** [comment]
Tab layout has been created.

**Comment by PhoenixTilea** [comment]
Functionally complete with some kind of data for every field. Finally!
