### ISSUE TITLE
Animal Food Sources

### ISSUE THREAD

**Issue by PhoenixTilea** [Nerdbuilding/Generator_Issue_Tracker#4]
Some places generate with a predatory animal and nothing it could eat to survive. Wild animals definitely need a lot of work, but food sources is something we should consider going forward. Also, it might be a little awkward calling something like a grizzly bear a "resource", but that's more a semantic/organization issue.

**Comment by thebeardedheathen** [comment]
This is something I had been thinking about. If we add in the need for carnivorous/predatory animals to have prey, then maybe we should also add in the requirement for Livestock and herbivores to have adequate feed and flora?

Also, it would be prudent to add in tags for Carnivorous, Omnivorous, Herbivorous.

**Comment by thebeardedheathen** [comment]
Added tags to wild animals:

Carnivore
Omnivore
Herbivore
Predator
Prey

**Comment by thebeardedheathen** [comment]
Wild animals have been updated with their required sources of food.

**Comment by thebeardedheathen** [comment]
Livestock have been updated with their required food sources
