### ISSUE TITLE
Site Feedback Form

### ISSUE THREAD

**Issue by PhoenixTilea** [Nerdbuilding/Generator_Issue_Tracker#5]
While it's nice and organized to have all the issues tracked here, I know that GitHub isn't the most convenient place for non-developers. As much as I wasn't sure about it, having an actual feedback form on the site is probably a good UX decision.

**Comment by thebeardedheathen** [comment]
A contact form/feedback form would be nice. If there is a way to create an "issue dropdown" so that we can restrict the subjects of the feedback to match the labels on Github, plus a generic "Contact us" label, I believe that would make it a little easier to keep track of them.

**Comment by PhoenixTilea** [comment]
Done for pre-alpha0.0.2
