### ISSUE TITLE
Generated information overlapping containers

### ISSUE THREAD

**Issue by thebeardedheathen** [Nerdbuilding/Generator_Issue_Tracker#70]
Some sections of generated content are overlapping the borders of the generator.

**Comment by thebeardedheathen** [comment]
Overlapping is happening, specifically at the bottom of the div

**Comment by thebeardedheathen** [comment]
Only able to recreate the issue in the Firefox browser.

**Comment by PhoenixTilea** [comment]
This seems to be some weird styling bug on Firefox specifically. We "fixed" it by making the area it overflows scrollable: not our first choice but it won't work any other way.
