### ISSUE TITLE
Settlement Order

### ISSUE THREAD

**Issue by thebeardedheathen** [Nerdbuilding/Generator_Issue_Tracker#79]
Re ordering the "Settlement Type" dropdown by size of settlement rather than alphabetically, would make the selection process a bit easier.

**Comment by thebeardedheathen** [comment]
We have begun switching to a new DB and the settlement order has been fixed. But, now landscapes and landforms need to be adjusted.

**Comment by PhoenixTilea** [comment]
Landforms and landscapes are alphabetical once more. Governments, races, and religions are not, but these are smaller lists. Should I sort them in the code, or should they just be moved around in the database? (Also, we should decide on an ordering for water features)

**Comment by thebeardedheathen** [comment]
I will just move the smaller lists, like races and religions around in the DB. Those are going to be changing drastically when we get into the social tabs and NPCs. For the water features, I will just order them in "apparent size"

**Comment by PhoenixTilea** [comment]
Dropdowns should now be ordered in a more intuitive way.
