### ISSUE TITLE
Flora Coverage Percentage - Based on Water Features

### ISSUE THREAD

**Issue by thebeardedheathen** [Nerdbuilding/Generator_Issue_Tracker#8]
Certain landscapes and biomes have little or no flora coverage, but the existence of rivers/lakes should increase the percentage of flora coverage.

**Comment by thebeardedheathen** [comment]
Water features have been updated with ground cover ranges.

**Comment by PhoenixTilea** [comment]
Fresh and brackish water sources now add to a settlement's ground cover percentage, which allows coverage in deserts. Update script should handle this when an old settlement is loaded.
