### ISSUE TITLE
Other Export Options

### ISSUE THREAD

**Issue by thebeardedheathen** [Nerdbuilding/Generator_Issue_Tracker#91]
In addition to the BBCode export option now available. We have identified partners who use other systems of formatting. and will implement the ability to export generated content into various different formats, such as:

-Markdown
-HTML
-Textile

Hopefully these four main styles will allow the widest range of usability for users of the generator.

**Comment by PhoenixTilea** [comment]
HTML should be good to go. The blank lines needed for Textile have caused me a bit of grief with the way I'm doing this, and I currently have the markdown format relying on Textile, so those two might take a bit longer.
