### ISSUE TITLE
World Anvil API import, setting new article to "NSFW" by default

### ISSUE THREAD

**Issue by thebeardedheathen** [Nerdbuilding/Generator_Issue_Tracker#98]
When a settlement article is created using the API, it is setting the the value of "NSFW" to true.

NSFW does not have an option to have it set by default. so somehow the article is getting set during import. Perhaps it would need to be specifically stated as "Not NSFW" during import.

isAdultContent | 0 \| 1 | 0 | bool | NSFW/18+ Flag for article

**Comment by PhoenixTilea** [comment]
The API docs state that this value defaults to 0 and I am not setting it for the export. I will explicitly set it to 0, but if that doesn't work, it's a problem on WorldAnvil's end.
